# Generated by Django 4.0.4 on 2022-04-12 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("custodial", "custodial")], max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("error", models.CharField(blank=True, max_length=100, null=True)),
                ("errors", models.CharField(blank=True, max_length=100, null=True)),
                ("result", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Key",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("local", "local"),
                            ("aws_kms", "aws_kms"),
                            ("google_kms", "google_kms"),
                        ],
                        max_length=20,
                    ),
                ),
                ("public_key", models.TextField()),
                ("sign_algo", models.CharField(max_length=100)),
                ("hash_algo", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
